# Generated by Django 3.2.4 on 2021-06-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210602_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
    ]
