# Generated by Django 3.2.4 on 2021-06-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employees_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='dept',
            field=models.ForeignKey(blank=True, default='IBMS', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
