# Generated by Django 3.2.4 on 2021-06-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210603_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
    ]
