# Generated by Django 3.2.4 on 2021-06-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employees_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='cnic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
