# Generated by Django 3.2.4 on 2021-06-03 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employees_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='dept',
            field=models.ForeignKey(blank=True, default='IBMS', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
    ]
